name: "Get pr info"
description: "Get pr info"

inputs:
  prId:
    description: "Pr id"
    required: true
    default: '${{ github.event.pull_request.number }}'
  prApprove:
    description: "PR approve"
    required: true
    default: 'false'

runs:
  using: "composite"
  steps:
  - name: Get pr info
    uses: stevei5mc/Get-PR-info-action@main
    id: getPrInfo
    with:
      prId: '${{ inputs.prId }}'
  - name: Set pull request env info
    shell: bash
    run: |
      echo "targetRef=$(echo pull/${{ inputs.prId }}/merge | sed 's/\//\\\//g')" >> $GITHUB_ENV
      echo "targetSha=$(echo ${{ steps.getPrInfo.outputs.headSha }} | cut -c 1-7)" >> $GITHUB_ENV
      echo "baseSha=$(echo ${{ steps.getPrInfo.outputs.baseSha }} | cut -c 1-7)" >> $GITHUB_ENV
      echo "baseUrl=$(echo ${{ steps.getPrInfo.outputs.baseRepoUrl }} | sed 's/\//\\\//g')" >> $GITHUB_ENV
      echo "baselabel=$(echo ${{ steps.getPrInfo.outputs.baseLabel }} | sed 's/\//\\\//g')" >> $GITHUB_ENV
      echo "headUrl=$(echo ${{ steps.getPrInfo.outputs.headRepoUrl }} | sed 's/\//\\\//g')" >> $GITHUB_ENV
      echo "headlabel=$(echo ${{ steps.getPrInfo.outputs.headLabel }} | sed 's/\//\\\//g')" >> $GITHUB_ENV
      echo "prUrl=$(echo ${{ steps.getPrInfo.outputs.htmlUrl }} | sed 's/\//\\\//g')" >> $GITHUB_ENV
  - name: Pull request summary
    shell: bash
    run: |
      templateFile=.github/template/pr-summary.md
      sed -i 's|{1A}|${{ inputs.prId }}|g; s|{1B}|${{ env.prUrl }}|g' $templateFile
      sed -i 's|{2}|${{ steps.getPrInfo.outputs.commits }}|g; s|{3}|${{ steps.getPrInfo.outputs.prState }}|g' $templateFile
      sed -i 's|{4}|${{ steps.getPrInfo.outputs.additions }}|g; s|{5}|${{ steps.getPrInfo.outputs.deletions }}|g; s|{6}|${{ steps.getPrInfo.outputs.changedFiles }}|g' $templateFile
      sed -i 's|{7}|${{ steps.getPrInfo.outputs.requestUser }}|g' $templateFile
      sed -i 's|{8A}|${{ env.headlabel }}|g; s|{8B}|${{ env.headUrl }}|g; s|{8C}|${{ env.targetSha }}|g' $templateFile
      sed -i 's|{9A}|${{ env.baselabel }}|g; s|{9B}|${{ env.baseUrl }}|g; s|{9C}|${{ env.baseSha }}|g' $templateFile
      cat $templateFile >> $GITHUB_STEP_SUMMARY
  - name: Pull request status check
    uses: actions/github-script@v8
    with:
      script: |
        core.info('Check current pull request state');
        if ('${{ steps.getPrInfo.outputs.prState }}' != 'open') {
          core.setFailed('Pull request state is ${{ steps.getPrInfo.outputs.prState }}');
        }else {
          core.info('Pull request state is ${{ steps.getPrInfo.outputs.prState }}');
        }