name: "Releases to minebbs"
description: "Releases to minebbs"

inputs:
  token:
    description: "Minebbs token"
    required: true
  version:
    description: "Release version"
    required: true

runs:
  using: "composite"
  steps:
  - name: Release to minebbs for Nukkit edition
    uses: engsr6982/upload-minebbs@v1.2.0
    with:
      minebbs_token: ${{ inputs.token }}
      resource_id: "12345"
      upload_file: ./bbs/Nukkit/*.*
      update_title: ${{ inputs.version }}
      update_version: ${{ inputs.version }}