name: "Releases mode"
description: "Releases version mode"

inputs:
  version:
    description: "Release version"
    required: true

outputs:
  releaseType:
    description: "Release type"
    value: ${{ steps.setRelease.outputs.releaseType }}
  prerelease:
    description: "Prerelease state"
    value: ${{ steps.setRelease.outputs.preRrelease }}

runs:
  using: "composite"
  steps:
  - name: Set release mode
    id: setRelease
    shell: bash
    run: |
      if echo ${{ inputs.version }} | grep -q "*-beta*"; then
        echo "Release version is beta version"
        echo "releaseType=beta" >> $GITHUB_OUTPUT
        echo "prerelease=true" >> $GITHUB_OUTPUT
      else
        echo "Release version is latest version"
        echo "releaseType=latest" >> $GITHUB_OUTPUT
        echo "prerelease=false" >> $GITHUB_OUTPUT
      fi