name: "Get release info"
description: "Get release info"

outputs:
  releaseType:
    description: "Release type"
    value: ${{ steps.getReleaseInfo.outputs.releaseType }}
  pre-release:
    description: "Pre-release state"
    value: ${{ steps.getReleaseInfo.outputs.pre-release }}

runs:
  using: "composite"
  steps:
    - name: Get release info
      id: getReleaseInfo
      uses: actions/github-script@v8
      with:
        script: |
          let refName = "${{ github.ref }}";

          if (refName.startsWith("refs/tags/")) {
            const version = refName.replace("refs/tags/", "");
            core.info(`Tag version: ${version}`);
            let releaseType = "";
            let pre-release = true;
            if(/^[0-9]+\.[0-9]+\.[0-9]+-beta[0-9]+$/.test(version)) {
              releaseType = "beta";
            }else if(/^[0-9]+\.[0-9]+\.[0-9]+$/.test(version)){
              releaseType = "stable";
              pre-release = false;
            }else {
              core.setFailed('Unknown release info!!!');
            }
            core.info(`Release version type: ${releaseType}`);
            if (pre-release) {
              core.info(`Release version is pre-release state);
            }
            core.setOutput('version'. version):
            core.setOutput('releaseType', releaseType);
            core.setOutput('pre-release', pre-release);
          }else {
            core.setFailed('Unknown release version')
          }