platform/Nukkit:
  - changed-files:
    - any-glob-to-any-file: Nukkit/src/main/**

platform/WDPE:
  - changed-files:
    - any-glob-to-any-file: WaterdogPE/src/main/**

type/feature:
  - head-branch: '^feat/.+$'

type/enhancement:
  - head-branch: '^ci/.+$'
