name: ServerHelper
main: cn.stevei5mc.serverhelper.nukkit.ServerHelperMain
version: "${version}"
author: stevei5mc
api: ["1.0.0"]

permissions:
  serverhelper.admin:
    default: op
    description: "插件主权限"
  serverhelper.admin.reload:
    default: op
    description: "重载配置文件"
  serverhelper.admin.unban.commands:
    default: op
    description: "解除命令的禁用状态"