name: "Upload test report files"
description: "Upload test report files"

inputs:
  artifactName:
    description: "Artifact name"
    required: true
    default: ServerHelper-Test_report_logs

runs:
  using: "composite"
  steps:
    - name: 上传报告文件
      uses: actions/upload-artifact@v7
      with:
        name: ${{ inputs.artifactName }}
        path: |
          ./Common/build/reports/tests
          ./Nukkit/build/reports/tests