name: "Upload artifact"
description: "Upload artifact"

inputs:
  artifactName:
    description: "Artifact suffix name"
    required: true
  artifactSaveDays:
    description: "90"
    required: true

runs:
  using: "composite"
  steps:
    - name: Upload Nukkit artifact
      uses: actions/upload-artifact@v4
      with:
        name: ServerHelper-Nukkit-${{ inputs.artifactName }}
        path: Nukkit/target
        retention-days: ${{ inputs.artifactRetentionDays }}
    - name: Upload WaterdogPE artifact
      uses: actions/upload-artifact@v4
      with:
        name: ServerHelper-WaterdogPE-${{ inputs.artifactName }}
        path: WaterdogPE/target
        retention-days: ${{ inputs.artifactSaveDays }}