name: "Cache gradle"
description: "Cache gradle"

runs:
  using: "composite"
  steps:
    - name: Build project
      shell: bash
      run: |
        chmod 777 gradlew && ls -lah
        ./gradlew shadowJar javadocJar
    - name: Get artifact hash
      shell: bash
      run: bash .github/workflows/scripts/getArtifactHash.sh