name: "Get project info"
description: "Get project info"

outputs:
  repoNmae:
    description: "Repo name"
    value: ${{ steps.getProjectBaseInfo.outputs.repo_name }}
  actionUrl:
    description: "Action url"
    value: ${{ steps.getProjectBaseInfo.outputs.actionUrl }}

runs:
  using: "composite"
  steps:
  - name: Get project info
    id: getProjectInfo
    shell: bash
    run: |
      echo "repo_name=${GITHUB_REPOSITORY/${{ github.repository_owner }}\//}" >> $GITHUB_OUTPUT
      echo "actionUrl=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_OUTPUT
      echo "targetSha=$(echo ${{ inputs.targetSha }} | cut -c 1-7)" >> $GITHUB_ENV
      echo "targetRef=$(echo ${{ inputs.targetRef }} | sed 's/refs\///g' | sed 's/heads\///g' | sed 's/\//\\\//g')" >> $GITHUB_ENV