name: "Get project info"
description: "Get project info"

inputs:
  targetSha:
    description: "Target sha"
    required: true
    default: ${{ github.sha }}
  targetRef:
    description: "Target ref"
    required: true
    default: ${{ github.ref }}

outputs:
  repoNmae:
    description: "Repo name"
    value: ${{ steps.getProjectInfo.outputs.repoName }}
  actionUrl:
    description: "Action url"
    value: ${{ steps.getProjectInfo.outputs.actionUrl }}
  releaseType:
    description: "Release type"
    value: ${{ steps.getProjectnfo.outputs.releaseType }}
  prerelease:
    description: "Prerelease state"
    value: ${{ steps.getProjectInfo.outputs.preRrelease }}

runs:
  using: "composite"
  steps:
  - name: Get project info
    id: getProjectInfo
    uses: actions/github-script@v8
    with:
      script: |
        let repoName = "${{ github.repository }}";
        let refName = "${{ inputs.targetRef }}";
        const commitId = "${{ inputs.targetSha }}";

        core.setOutput('actionUrl', "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}");

        repoName = repoName.replace("${{ github.repository_owner }}/", "");
        core.info(`Repo name: ${repoName}`);
        core.setOutput('repoName', repoName);

        const targetBranch = refName.replace("refs/", "").replace("heads/", "");
        const commitIdShort = commitId.substring(0, 7);
        core.exportVariable('targetBranch', targetBranch);
        core.exportVariable('targetCommitId', commitIdShort);

        if (refName.startsWith("refs/tags/")) {
          const version = refName.replace("refs/tags/", "");
          core.log(`Tag version: ${version}`);
          let releaseType = "";
          let preRelease = true;
          if(/^[0-9]+.[0-9]+.[0-9]+-beta[0-9]+$/.test(version)) {
            releaseType = "beta";
          }else if(/^[0-9]+.[0-9]+.[0-9]+$/.test(version)){
            releaseType = "stable";
            preRelease = false;
          }else {
            core.setFailed('Unknown release info!!!');
          }
          core.info(`Release version type: ${releaseType}`);
          core.info(`Release version is preRelease: ${preRelease}`);
          core.setOutput('releaseType', releaseType);
          core.setOutput('preRelease', preRelease);
        }