name: "Get maven project pom info"
description: "Get maven project pom info"

inputs:
  pomPath:
    description: "Maven project pom.xml path"
    required: true

outputs:
  pomHash:
    description: "pom.xml file hash"
    value: ${{ steps.pomInfo.outputs.pomHash }}
  groupId:
    description: "Maven project group id"
    value: ${{ steps.pomInfo.outputs.groupId }}
  artifactId:
    description: "Maven project artifact id"
    value: ${{ steps.pomInfo.outputs.artifactId }}
  version:
    description: "Maven project version"
    value: ${{ steps.pomInfo.outputs.version }}

runs:
  using: "composite"
  steps:
  - name: Get pom.xml info
    id: pomInfo
    shell: bash
    run: |
      echo "pomHash=$(sha256sum ./${{ inputs.pomPath }}/pom.xml|awk '{print $1}')" >> $GITHUB_OUTPUT
      echo "groupId=$(mvn help:evaluate -f ${{ inputs.pomPath }} -Dexpression=project.groupId -q -DforceStdout)" >> $GITHUB_OUTPUT
      echo "artifactId=$(mvn help:evaluate -f ${{ inputs.pomPath }} -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_OUTPUT
      echo "version=$(mvn help:evaluate -f ${{ inputs.pomPath }} -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
  - name: Print pom.xml info
    shell: bash
    run: |
      echo pom.xml file hash ${{ steps.pomInfo.outputs.pomHash }}
      echo Group id: ${{ steps.pomInfo.outputs.groupId }}
      echo Artifact id: ${{ steps.pomInfo.outputs.artifactId }}
      echo Version: ${{ steps.pomInfo.outputs.version }}