name: "Cache gradle"
description: "Cache gradle"

runs:
  using: "composite"
  steps:
  - name: Get cache key
    id: get
    shell: bash
    run: |
      echo "cacheKey=$(sha256sum *.kts gradle.properties ./Common/*.kts ./Nukkit/*.kts ./WaterdogPE/*.kts  ./gradle/*.* ./gradle/wrapper/* | sha256sum | awk '{print $1}')" >> $GITHUB_OUTPUT
  - name: Cache Gradle
    uses: actions/cache@v4
    with:
      path: |
        ~/.gradle/caches
        ~/.gradle/wrapper
      key: ${{ runner.os }}-GRADLE-${{ steps.get.outputs.cacheKey }}
      restore-keys: ${{ runner.os }}-GRADLE-