name: dispatch

on:
  workflow_dispatch:
    inputs:
      buildMode:
        description: 'Build mode'
        required: false
        default: 'Plugin'
        type: choice
        options: ['Plugin','All']
      gradleExpandParameters:
        description: 'Gradle build expand parameters'
        required: false
      artifactSaveDays:
        description: "Artifact retention days"
        required: false
        default: '90'
        type: choice
        options: ['0','1','7','14','30','60','90']
      additionalFunctions:
        description: "Additional functions"
        required: false
        default: 'Not used'
        type: choice
        options: ['Not used','Build PR','Release snapshot','Delete snapshot']
      PR_ID:
        description: 'PR number'
        required: false

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  Initialize:
    runs-on: ubuntu-slim
    timeout-minutes: 5
    outputs:
      actionUrl: ${{ steps.getProjectInfo.outputs.actionUrl }}
      targetCommitId: ${{ env.targetCommitId }}
      targetBranch: ${{ env.targetBranch }}
      prState: ${{ steps.prInfo.outputs.prState }}
      repoName: ${{ steps.getProjectInfo.outputs.repoNmae }}
    steps:
      - name: 拉取代码
        uses: actions/checkout@v6
      - name: 处理和检查输入的参数
        uses: actions/github-script@v8
        with:
          script: |
            const additionalFunctions = "${{ inputs.additionalFunctions }}";
            if (additionalFunctions == 'Build PR') {
              const PR_ID = "${{ inputs.PR_ID }}";
              const prNumber = Number(PR_ID.trim());
              if (!Number.isInteger(prNumber) || prNumber <= 0) {
                core.setFailed(`输入的PR编号格式不正确。输入值为: ${PR_ID}`);
              }
            }
            if (additionalFunctions == 'Release snapshot' && ${{ inputs.artifactSaveDays }} < 1) {
              core.setFailed(`构建后的 artifact 保存天数为 ${{ inputs.artifactSaveDays }}，必须 >= 1，否则无法正常发布快照版本`);
            }
      - name: 获取信息
        id: getProjectInfo
        uses: ./.github/actions/getProjectInfo
      - name: Summary base info
        run: |
          cat << EOF >> $GITHUB_STEP_SUMMARY
          # BUILD INFO
          |Tatget ref|Target sha|Artifact save days|
          |:-:|:-:|:-:|
          EOF
          if [ '${{ inputs.additionalFunctions }}' == 'Build PR' ]; then
            echo "|===|===|${{ inputs.artifactSaveDays }}|" >> $GITHUB_STEP_SUMMARY
          else
            echo "|${{ env.targetBranch }}|${{ env.targetCommitId }}|${{ inputs.artifactSaveDays }}|" >> $GITHUB_STEP_SUMMARY
          fi
      - name: Get and summary PR info
        if: inputs.additionalFunctions == 'Build PR'
        id: prInfo
        uses: ./.github/actions/getPrInfo
        with:
          prId: ${{ inputs.PR_ID }}
          prApprove: true
      - name: 删除快照
        if: inputs.additionalFunctions == 'Release snapshot' || inputs.additionalFunctions == 'Delete snapshot'
        run: |
          if gh release view snapshot-version >/dev/null 2>&1; then
            echo "正在删除快照版本"
            gh release delete snapshot-version --yes --cleanup-tag
          fi

  build-plugin:
    if: ((inputs.buildMode == 'Plugin' || inputs.buildMode == 'All') && inputs.additionalFunctions != 'Delete snapshot') || inputs.additionalFunctions == 'Build PR' || inputs.additionalFunctions == 'Release snapshot'
    name: Build plugin
    needs: Initialize
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      java-version: "17"
    steps:
      - name: 拉取代码
        uses: actions/checkout@v6
      - name: 拉取 PR 代码
        if: inputs.additionalFunctions == 'Build PR'
        run: gh pr checkout ${{ inputs.PR_ID }} && ls -la
      - name: Setup java ${{ env.java-version }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.java-version }}
          distribution: 'temurin'
      - name:  Cache local Gradle wrapper and repository
        uses: ./.github/actions/cacheGradle
      - name: Replace info
        run: |
          classPath=Common/src/main/java/cn/stevei5mc/serverhelper/common/BaseInfo.java
          version=$(grep "project.version=" "./gradle.properties" | sed 's/project.version=//')
          sed -i 's|{git.commit.id}|${{ needs.Initialize.outputs.targetCommitId }}|g; s|{git.branch}|${{ needs.Initialize.outputs.targetBranch }}|g; s|{project.version}|'"$version"'|g' $classPath
      - name: Set gradlew 777 permission
        run: chmod 777 gradlew && ls -lah
      - name:  Build project
        run: ./gradlew shadowJar javadocJar --no-daemon --parallel ${{ inputs.gradleExpandParameters }}
      - name: Get artifact hash and copy files
        if: inputs.artifactSaveDays >= 1
        run:  bash .github/workflows/scripts/getHashAndCopy.sh
      - name: Upload artifact
        if: inputs.artifactSaveDays >= 1
        uses: actions/upload-artifact@v6
        with:
          name: ${{ needs.Initialize.outputs.repoName }}-Dispatch-Build_${{ github.run_number }}
          retention-days: ${{ inputs.artifactSaveDays }}
          path: ./staging

  post-processing:
    if: needs.build-plugin.result == 'success' && inputs.additionalFunctions == 'Release snapshot'
    needs: [Initialize, build-plugin]
    runs-on: ubuntu-slim
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - name: 拉取代码
        uses: actions/checkout@v6
      - name: 下载发布需要的文件
        if: inputs.additionalFunctions == 'Release snapshot'
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.Initialize.outputs.repoName }}-Dispatch-Build_${{ github.run_number }}
          path: staging
      - name: 整理和校验需要发布的文件
        if: inputs.additionalFunctions == 'Release snapshot'
        run: |
          echo "branch=$(echo ${{ needs.Initialize.outputs.targetBranch }})" >> $GITHUB_ENV
          ls -lah ./staging
          version=$(grep "project.version=" "./gradle.properties" | sed 's/project.version=//')
          bash .github/workflows/scripts/verifyHash.sh "./staging" "ServerHelper-$version-all_files.sha256"
          rm -f ./staging/ServerHelper-$version-all_files.sha256
      - name: 发布快照版本
        if: inputs.additionalFunctions == 'Release snapshot'
        run: |
          cat > ./release_notes.md << 'EOF'
          > [!NOTE]
          该版本为快照版本，仅供体验测试使用，若在生产环境中使用需谨慎考虑！！！
          快照版本对应分支为 `${{ env.branch }}`
          EOF
          gh release create snapshot-version ./staging/*.* --prerelease --target "${{ env.branch }}" --title "Snapshot version" --notes-file ./release_notes.md
          gh release view snapshot-version