name: PR check

on:
  pull_request:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  Initialize:
    runs-on: ubuntu-latest
    outputs:
      repo_name: ${{ steps.get_info.outputs.repoNmae }}
      targetSha: ${{ env.targetSha }}
      targetRef: ${{ env.targetRef }}
    steps:
    - name: 拉取代码
      uses: actions/checkout@v4
    - name: 获取信息
      id: get_info
      uses: ./.github/actions/getProjectInfo
    - name: Summary PR info
      uses: ./.github/actions/getPrInfo

  build-plugin:
    name: Build plugin
    needs: Initialize
    runs-on: ubuntu-latest
    env:
      java-version: "17"
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: Setup java ${{ env.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.java-version }}
          distribution: 'temurin'
      - name:  Cache local Gradle wrapper and repository
        uses: ./.github/actions/cacheGradle
      - name: Replace info
        run: |
          classPath=Common/src/main/java/cn/stevei5mc/serverhelper/common/utils/BaseInfo.java
          version=$(grep "version =" "./build.gradle.kts" | sed 's/.*version = "\(.*\)".*/\1/')
          sed -i 's/{git.commit.id}/${{ needs.Initialize.outputs.targetSha }}/g; s/{git.branch}/${{ needs.Initialize.outputs.targetRef }}/g; s/{project.version}/$version/g' $classPath
      - name:  Build project
        run: |
          chmod 777 gradlew && ls -lah
          ./gradlew shadowJar javadocJar --no-daemon
      - name: Get artifact hash
        run: bash .github/workflows/scripts/getArtifactHash.sh
      - name: Prepare releases files
        run: bash .github/workflows/scripts/prepareReleasesFiles.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.Initialize.outputs.repo_name }}-PR_${{ github.event.pull_request.number }}_check-Build_${{ github.run_number }}
          path: ./staging

#  build-Docusaurus:
#    name: Build docusaurus
#    needs: Initialize
#    runs-on: ubuntu-latest
#    steps:
#    - name: 拉取代码
#      uses: actions/checkout@v4
#    - uses: actions/setup-node@v4
#      with:
#        node-version: 18
#    - name: 构建
#      run: |
#        cd Docusaurus
#        yarn install --frozen-lockfile
#        yarn build
#        cd ../
#    - name: 上传构建
#      uses: actions/upload-pages-artifact@v3
#      with:
#        path: Docusaurus/build