name: PR check

on:
  workflow_dispatch:
    inputs:
      build-plugin:
        description: 'Build plugin'
        required: false
        default: true
        type: boolean
      build-Docusaurus:
        description: 'Build docusaurus'
        required: false
        default: false
        type: boolean
      deploy-gitHub-pages:
        description: 'Deploy gitHub pages'
        required: false
        default: false
        type: boolean
      PR_Approve:
        description: 'PR Approve'
        required: false
        default: false
        type: boolean
      PR_ID:
        description: 'PR Approve ID'
        required: false

jobs:
  initialize:
    runs-on: ubuntu-latest
    outputs:
      repo_name: ${{ steps.get_info.outputs.repo_name }}
      artifact_name: ${{ steps.get_info.outputs.repo_name }}-Dispatch-Build_${{ github.run_number }}
    steps:
    - name: 获取信息
      id: get_info
      run: |
        echo "repo_name=${GITHUB_REPOSITORY/${{ github.repository_owner }}\//}" >> $GITHUB_OUTPUT

  build-plugin:
    strategy:
      matrix:
        include:
          - name: "Nukkit"
            path: "Nukkit"
            java: '8'
          - name: "WaterdogPE"
            path: "WaterdogPE"
            java: '17'
    runs-on: ubuntu-latest
    needs: initialize
    name: Build ${{ matrix.name }} Edition
    steps:
    - name: 拉取代码
      uses: actions/checkout@v4.1.6
    - name: 拉取代码(批准PR专用)
      if: needs.initialize.outputs.PR_Approve == 'true' && needs.initialize.outputs.Deploy_gitHub_pages == 'false'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ls -la
        gh pr checkout ${{ inputs.PR_ID }}
        ls -la
    - name: Setup java ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    - name: Get pom.xml hash
      id: pom_hash
      run: |
        cd ./${{ matrix.path }}
        echo "pom_hash=$(sha256sum pom.xml|awk '{print $1}" >> $GITHUB_OUTPUT
        cd ../
    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ matrix.name }}_edition-${{ steps.pom_hash.outputs.pom_hash }}
        restore-keys: |
          ${{ runner.os }}-maven--${{ matrix.name }}_edition-
    - name: Build
      run: |
        cd ${{ matrix.path }}
        mvn -B package --file pom.xml
        mkdir staging
        cp target/*.jar staging
        cd ../
    - name: Get Build artifact hash
      run: |
        pwd
        cd ./${{ matrix.path }}/staging
        pwd
        touch ${{ matrix.name }}_edition-hash-sha256.txt
        touch ${{ matrix.name }}_edition-hash-md5.txt
        sha256sum *.jar | tee ${{ matrix.name }}_edition-hash-256.txt
        md5sum *.jar | tee ${{ matrix.name }}_edition-hash-md5.txt
        mv ./${{ matrix.name }}_edition-hash-sha256.txt ./${{ matrix.name }}_edition-hash-sha256-$(sha256sum ${{ matrix.name }}_edition-hash-sha256.txt|awk '{print $1}').txt
        mv ./${{ matrix.name }}_edition-hash-md5.txt ./${{ matrix.name }}_edition-hash-md5-$(md5sum ${{ matrix.name }}_edition-hash-md5.txt|awk '{print $1}').txt
        cd ../../
    - name: Upload build artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: ${{ needs.initialize.outputs.artifact_name }}-for_${{ matrix.name }}_Edition
        path: ${{ matrix.path }}/staging

  build-Docusaurus:
    name: Build docusaurus
    needs: initialize
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: 拉取代码(批准PR专用)
        if: needs.initialize.outputs.PR_Approve == 'true' && needs.initialize.outputs.Deploy_gitHub_pages == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls -la
          gh pr checkout ${{ inputs.PR_ID }}
          ls -la
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: 构建
        run: |
          cd Docusaurus
          npm ci
          npm run build
          cd ../
      - name: 上传构建
        uses: actions/upload-pages-artifact@v3
        with:
          path: Docusaurus/build