name: PR check

on:
  pull_request:

jobs:
  initialize:
    runs-on: ubuntu-latest
    outputs:
      repo_name: ${{ steps.get_info.outputs.repo_name }}
      artifact_name: ${{ steps.get_info.outputs.repo_name }}-PR_${{ github.event.pull_request.number }}_check-Build_${{ github.run_number }}
    steps:
    - name: 获取信息
      id: get_info
      run: |
        echo "repo_name=${GITHUB_REPOSITORY/${{ github.repository_owner }}\//}" >> $GITHUB_OUTPUT

  build-plugin:
    strategy:
      matrix:
        include: [
          {name: "Nukkit",path: "Nukkit",java: '8'},
          {name: "WaterdogPE",path: "WaterdogPE",java: '17'}
        ]
    runs-on: ubuntu-latest
    needs: initialize
    name: Build ${{ matrix.name }} Edition
    steps:
    - name: 拉取代码
      uses: actions/checkout@v4.1.6
    - name: Setup java ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    - name: Extractor pom.xml gav info 
      uses: andreacomo/maven-gav-extractor@v2.0.1
      id: getPomInfo
      with:
        pom-location: ./${{ matrix.path }}/pom.xml 
    - name: Show get pom.xml gav info
      run: |
        echo ${{ steps.getPomInfo.outputs.group-id }}
        echo ${{ steps.getPomInfo.outputs.artifact-id }}
        echo ${{ steps.getPomInfo.outputs.version }}
    - name: Get pom.xml hash
      id: pom_hash
      run: echo "pom_hash=$(sha256sum ./${{ matrix.path }}/pom.xml|awk '{print $1}')" >> $GITHUB_OUTPUT
    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ matrix.name }}_edition-${{ steps.pom_hash.outputs.pom_hash }}
        restore-keys: |
          ${{ runner.os }}-maven--${{ matrix.name }}_edition-
    - name: Build project and get artifact hash
      run: bash .github/workflows/buildMavenProjectAndGetHash.sh "${{ steps.getPomInfo.outputs.artifact-id }}" "${{ matrix.path }}"
    - name: Upload build artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: ${{ needs.initialize.outputs.artifact_name }}-for_${{ matrix.name }}_Edition
        path: ${{ matrix.path }}/staging

#  build-Docusaurus:
#    name: Build docusaurus
#    needs: initialize
#    runs-on: ubuntu-latest
#    steps:
#      - name: 拉取代码
#        uses: actions/checkout@v4
#        with:
#          submodules: true
#      - name: 拉取代码(批准PR专用)
#        if: needs.initialize.outputs.PR_Approve == 'true' && needs.initialize.outputs.Deploy_gitHub_pages == 'false'
#        env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          ls -la
#          gh pr checkout ${{ inputs.PR_ID }}
#          ls -la
#      - uses: actions/setup-node@v4
#        with:
#          node-version: 18
#      - name: 构建
#        run: |
#          cd Docusaurus
#          yarn install --frozen-lockfile
#          yarn build
#          cd ../
#      - name: 上传构建
#        uses: actions/upload-pages-artifact@v3
#        with:
#          path: Docusaurus/build