name: PR CI

on:
  pull_request:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  Initialize:
    runs-on: ubuntu-slim
    timeout-minutes: 5
    outputs:
      repoName: ${{ steps.getProjectInfo.outputs.repoNmae }}
      targetCommitId: ${{ env.targetCommitId }}
      targetBranch: ${{ env.targetBranch }}
    steps:
      - name: 拉取代码
        uses: actions/checkout@v6
      - name: 获取信息
        id: getProjectInfo
        uses: ./.github/actions/getProjectInfo
      - name: Get and summary PR info
        uses: ./.github/actions/getPrInfo

  build-plugin:
    name: Build plugin
    needs: Initialize
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      java-version: "17"
    steps:
      - name: 拉取代码
        uses: actions/checkout@v6
      - name: Setup java ${{ env.java-version }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.java-version }}
          distribution: 'temurin'
      - name:  Cache local Gradle wrapper and repository
        uses: ./.github/actions/cacheGradle
      - name: Replace info
        run: |
          classPath=Common/src/main/java/cn/stevei5mc/serverhelper/common/BaseInfo.java
          version=$(grep "project.version=" "./gradle.properties" | sed 's/project.version=//')
          sed -i 's|{git.commit.id}|${{ needs.Initialize.outputs.targetCommitId }}|g; s|{git.branch}|${{ needs.Initialize.outputs.targetBranch }}|g; s|{project.version}|'"$version"'|g' $classPath
      - name: Set gradlew 777 permission
        run: chmod 777 gradlew && ls -lah
      - name:  Build project
        run: ./gradlew shadowJar javadocJar --no-daemon --parallel ${{ inputs.gradleExpandParameters }}
      - name: Get artifact hash and copy files
        run:  bash .github/workflows/scripts/getHashAndCopy.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ needs.Initialize.outputs.repoName }}-PR_${{ github.event.pull_request.number }}_check-Build_${{ github.run_number }}
          path: ./staging