name: PR lebeler

concurrency:
  group: PR-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  pull_request_target:
    paths-ignore:
      - ".github/actions/getReleaseInfo/action.yml"
      - ".github/actions/releaseSnapshot/action.yml"
      - ".github/workflows/dispatch.yml"
      - ".github/workflows/tagpush.yml"

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  pr-labeler:
    runs-on: ubuntu-slim
    name: PR labeler
    timeout-minutes: 2
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: 拉取代码
        uses: actions/checkout@v6
      - name: 分配标签
        id: labeler
        uses: actions/labeler@v6
        with:
          sync-labels: true
          configuration-path: .github/labeler.yml